services:
  mysql:
    image: 'mysql'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql # since we use docker, this should be the same name as the service from the db