services:
  postgres:
    image: postgres:16.1
    container_name: recipe-postgress
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=cuisinedb_recipes'
    ports:
      - 5432:5432

  recipeservice:
    image: recipe-service:latest
    depends_on:
      - postgres
    ports:
      - 9001:8085
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://recipe-postgress:5432/cuisinedb_recipes'

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
  adminer:
    image: adminer
#    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: mysql # since we use docker, this should be the same name as the service from the db

  rabbitmq:
    image: rabbitmq:3.12.7-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq