# Config server
spring:
  application:
    name: recipe-service
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 5
        max-attempts: 5
        max-interval: 20
        multiplier: 1.3
      request-connect-timeout: 5000
      request-read-timeout: 5000
      uri: "http://localhost:8888"
  config:
    import: "optional:configserver:"