# Config server
spring:
  application:
    name: recipe-service
  cloud:
    config:
#      fail-fast: true
      retry:
        initial-interval: 5
        max-attempts: 5
        max-interval: 20
        multiplier: 1.3
      request-connect-timeout: 5000
      request-read-timeout: 5000
      uri: "http://localhost:8888"
  config:
    import: "optional:configserver:"
  datasource:
    url: "jdbc:postgresql://localhost:5432/cuisinedb_recipes"
    username: user
    password: secret
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
    #      naming:
    #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: false
  rabbitmq:
    listener:
      simple:
        # disable the default requeue behavior (source: https://programmerfriend.com/rabbit-mq-retry/)
        default-requeue-rejected: false
    username: guest
    password: guest
  sql:
    init:
      mode: always

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        #        refresh: enable hot reloading of properties via /actuator/refresh
        include: info,health,env,metrics,refresh
  endpoint:
    env:
      show-values: always
    health:
      show-components: always
      enabled: true
      probes:
        enabled: true
        add-additional-paths: true
      show-details: always
  health:
    rabbit:
      enabled: false
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

# Application properties

#app.rabbit.recipeCreatedListener.queueName=testje
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

app:
  recipe:
    greeting: hello world!
  rabbit:
    exchange: recipeservicex
    recipe-created-listener:
      queue-name: recipeservice.recipe-created
      routing-key: recipe-created
      dlx-name: dlx
  # enable rabbit integration. If set to false, a dummy message sender is used. Also we will not listen to events.
  fullblownrabbit: false
  # enable initialization of data
  initializedata: true
  data:
    inmemory: false
    # when put to true, an inmemory list of recipes is kept
    # when put to false, or is the property is absent, a mysql database is used for persistence
