name: Integration tests
on:
  workflow_dispatch:
  schedule:
    - cron: 0 5 * * *

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven
      - name: run tests
        run: |
          chmod +x mvnw
          ./mvnw package -Pintegrationtests
